---
# Install Cassandra
# moving this to common:
#- name: install java depends
#  apt: 
#    pkg: 
#      - openjdk-11-jdk
#      - openjdk-11-jdk-headless
#    state: present

- name: download Apache Cassandra GPG key
  get_url:
    url: "https://downloads.apache.org/cassandra/KEYS"
    dest: "/etc/apt/keyrings/apache-cassandra.asc"

- name: adding cassandra repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main"
    state: present

# version pin here
- name: install basic packages
  apt:
    pkg:
    - cassandra
    - cassandra-tools
    state: present
    update_cache: yes

- name: stop cassandra to configure cluster
  systemd: 
    name: cassandra
    state: stopped

# remove datadir to configure cluster with new name
- name: remove cassandra data directory 
  file:
    path: "{{ cassandra_datadir }}"
    state: absent

- name: create /var/lib/cassandra directory
  file:
    path: "{{ cassandra_datadir }}"
    state: directory
    owner: cassandra
    group: cassandra
    mode: '0755'    