---
# Install Cassandra
# moving this to common:
#- name: install java depends
#  apt: 
#    pkg: 
#      - openjdk-11-jdk
#      - openjdk-11-jdk-headless
#    state: present

- name: download Apache Cassandra GPG key
  get_url:
    url: "https://downloads.apache.org/cassandra/KEYS"
    dest: "/etc/apt/keyrings/apache-cassandra.asc"

- name: adding cassandra repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main"
    state: present

- name: install basic packages
  apt:
    pkg:
    - cassandra
    - cassandra-tools
    state: present
    update_cache: yes

- name: stop cassandra to create ssl and apply configs
  systemd: 
    name: cassandra
    state: stopped