---
- name: check nodetool status on each cassandra node
  command: nodetool status
  register: nodetool_output
  retries: 10 
  delay: 20  
  until: >
    (nodetool_output.stdout | regex_findall('UN') | length) >= 3

- name: create cassandra directory
  file:
    path: /root/.cassandra
    state: directory
    mode: "0700"

- name: create cqlsh connection conf
  template:
    src: cqlsh.j2
    dest: /root/.cassandra/cqlshrc
    owner: cassandra
    group: cassandra
    mode: '0644'
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['cassandra_servers'] }}"
  loop_control:
    index_var: count
      
- name: add superuser to db
  command: >
    cqlsh {{ cassandra_data.results[1].instance.hostname }} -u cassandra -p cassandra -e "CREATE ROLE {{ db_user }} WITH SUPERUSER = true AND LOGIN = true AND PASSWORD = '{{ db_password }}';"
  delegate_to: "{{ groups['cassandra_servers'][0] }}"

- name: alter default user
  command: >
    cqlsh {{ cassandra_data.results[1].instance.hostname }} -u {{ db_user }} -p {{ db_password }} -e "ALTER ROLE cassandra WITH SUPERUSER = false AND LOGIN = false;"
  delegate_to: "{{ groups['cassandra_servers'][0] }}"