---
# configure cassandra cluster

- name: creating cassandra config backup
  copy:
    src: '{{ cassandra_config_directory }}/cassandra.yaml'
    dest: '{{ cassandra_config_directory }}/cassandra.yaml.original'
    remote_src: yes
    owner: cassandra
    group: cassandra
    mode: 0644

- name: update cassandra config
  template:
    src: templates/cassandra.yaml.j2
    dest: '{{ cassandra_config_directory }}/cassandra.yaml'
  loop: "{{ groups['cassandra_servers'] }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop_control:
    index_var: count

- name: update data center region
  lineinfile:
    path: /etc/cassandra/cassandra-rackdc.properties 
    regexp: '^dc=dc1$'
    line: 'dc={{ region }}'

- name: create cassandra hidden directory
  file:
    path: /root/.cassandra
    state: directory
    mode: 0700

- name: create conf files in cassandra hidden dir
  template:
    src: templates/cqlshrc.j2
    dest: /root/.cassandra/cqlshrc
    mode: 0600
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['cassandra_servers'] }}"
  loop_control:
    index_var: count

- name: start cassandra
  systemd: 
    name: cassandra
    state: started