# Install Cassandra  
- name: install java depends
  apt: 
    pkg: openjdk-8-jdk=8u402-ga-2ubuntu1~22.04
    state: present

- name: download Apache Cassandra GPG key
  get_url:
    url: "https://downloads.apache.org/cassandra/KEYS"
    dest: "/etc/apt/keyrings/apache-cassandra.asc"

- name: adding cassandra repository
  apt_reposistory:
    repo: "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main"
    state: present

- name: install basic packages
  apt:
    pkg:
    - cassandra
    - cassandra-tools
    state: present
    update_cache: yes

