---
- name: creating cassandra config backup
  copy:
    src: "{{ cassandra_config }}"
    dest: "{{ cassandra_config }}.bak"
    remote_src: yes
    owner: cassandra
    group: cassandra
    mode: '0644'
 
- name: updating cassandra.yaml 
  template:
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config }}"
    owner: cassandra
    group: cassandra
    mode: '0644'
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['cassandra_servers'] }}"
  loop_control:
    index_var: count

- name: update seeds in conf
  replace:
    path: "{{ cassandra_config }}"
    regexp: '^(.*- seeds:).*'
    replace: |
      {% if cluster_size == 3 %}
            - seeds: "{{ cassandra_data.results[0].instance.ip_priv1 }}, {{ cassandra_data.results[1].instance.ip_priv1 }}, {{ cassandra_data.results[2].instance.ip_priv1 }}"
      {% elif cluster_size == 5 %}  
            - seeds: "{{ cassandra_data.results[0].instance.ip_priv1 }}, {{ cassandra_data.results[1].instance.ip_priv1 }}, {{ cassandra_data.results[2].instance.ip_priv1 }}, {{ cassandra_data.results[3].instance.ip_priv1 }}, {{ cassandra_data.results[4].instance.ip_priv1 }}" 
      {% endif %}

- name: stop cassandra service
  systemd:
    name: cassandra
    state: stopped

# removes sample data
- name: remove cassandra data directory 
  file:
    path: /var/lib/cassandra/
    state: absent

- name: recreate /var/lib/cassandra directory
  file:
    path: /var/lib/cassandra
    state: directory
    owner: cassandra
    group: cassandra
    mode: '0755'