---
# configure hostname and hosts file

- name: configure hostnames
  hostname:
    use: systemd
    name: "{{ cassandra_data.server[count].instance.hostname }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['cassandra_servers'] }}"
  loop_control:
    index_var: count

- name: update /etc/hosts on all of the nodes
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} cassandra servers"
    block: |
      #jinja2: trim_blocks:False
      # Cassandra
      {%- for count in range(cluster_size) %}
      {{ cassandra_data.server[count].instance.ip_priv1 }} {{ cassandra_data.server[count].instance.hostname }}
      {%- endfor %}    