# Install Cassandra  
- name: download Apache Cassandra GPG key
  get_url:
    url: "https://downloads.apache.org/cassandra/KEYS"
    dest: "/etc/apt/keyrings/apache-cassandra.asc"

- name: adding cassandra repository
  lineinfile:
    dest: /etc/apt/sources.list.d/cassandra.list
    line: "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main"
    state: present
    create: yes

- name: apt update
  apt:
    update_cache: yes

- name: install basic packages
  apt:
    pkg:
    - default-jre
    - cassandra
#    - cassandra-tools
    state: present

# - name: Install cassandra-driver using pip3
#   pip:
#     name: 
#       - cassandra-driver
#       - cqlsh 
#     executable: pip3

