# roles/common/tasks
# common tasks for all linodes
---
- name: configure hostnames
  hostname:
    use: systemd
    name: "{{ cassandra_data.server[count].instance.hostname }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['cassandra_cluster'] }}"
  loop_control:
    index_var: count

- name: update /etc/hosts on all of the nodes
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} cassandra servers"
    block: |
      #jinja2: trim_blocks:False
      # Cassandra
      {%- for count in range(cluster_count | int) %}
      {{ cassandra_data.server[count].instance.ip_priv1 }} {{ cassandra_data.server[count].instance.hostname }}
      {%- endfor %}

- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: full

- name: install basic packages
  apt:
    pkg:
    - net-tools
    - htop
    - rsync
    - fail2ban
    - ufw
    - software-properties-common  
    - gnupg2
    - ssl-cert
    state: present

- name: fail2ban jail.local
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: yes
  notify: start fail2ban

- name: secure ssh configs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '^\#?PermitRootLogin (yes|no)', replace: 'PermitRootLogin without-password' }
    - { search: '^\#?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { search: '^\#?PubkeyAuthentication (yes|no)', replace: 'PubkeyAuthentication yes' }
  notify: restart ssh

- name: apply ufw rules
  import_tasks: ufw_rules.yml